### ISSUE TITLE
Add lab caches to /statbar

### ISSUE THREAD

**Issue by wyattshanahan** [Technical-13/Signal#2]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to see my find count including lab caches when using the /statbar command,

**Describe the solution you'd like**
I propose implementing a second command, either to include caches in /statbar or to get the current version which excludes caches and modify /statbar itself.

**Describe alternatives you've considered**
An alternative solution would be to use arguments when users call the command and have one of the options as a default.

**Additional context**
Theoretically, one could use this link when retrieving the statbar with labcaches:

https://cdn2.project-gc.com/StatBar/USERNAME.png?includeLabcaches

**Comment by bwjmackie** [comment]
The command already includes lab caches.
![image](https://github.com/user-attachments/assets/9ddb86b0-1bff-418f-8c9f-25e36aab589c)
Would you clarify your request?

**Comment by Technical-13** [comment]
> The command already includes lab caches.
> ![image](https://github.com/user-attachments/assets/9ddb86b0-1bff-418f-8c9f-25e36aab589c)
> Would you clarify your request?

I believe the request is to make it toggleable.

**Comment by wyattshanahan** [comment]
At the time of submission, the command did not show lab caches. That said, it being toggleable would be the ideal implementation

**Comment by Technical-13** [comment]
> At the time of submission, the command did not show lab caches. That said, it being toggleable would be the ideal implementation

![Screenshot_20240718-080916.png](https://github.com/user-attachments/assets/bc94271a-6ec4-408b-87d9-11551d47501b)

Look at the link. It certainly did. I haven't changed it since I made it, it's always been default included. I don't have a working computer right now, but when I do I'll add the option to turn it off.

**Comment by Technical-13** [comment]
Nothing to do here.
