### ISSUE TITLE
User global display names not used for statbar, etc. commands

### ISSUE THREAD

**Issue by bwjmackie** [Technical-13/Signal#3]
**Describe the bug**
User with the following setup:
- Server-specific nickname: Unset
- Global profile display name: JSmith123
- Discord username: jsmith123
- Geocaching username: JSmith123
When this user runs /statbar (or other similar commands) with no other parameters, the script attempts to identify the person running the command first by using their server-specific nickname, and if unset, falls back to their Discord username.  This results in using the wrong username for the generated output.

**To Reproduce**
See above.

**Expected behavior**
As a second priority, the scripts should check for a global profile display name and use that before falling back to the Discord username.  This data is available in interaction.user.global_name.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Technical-13** [comment]
Should be resolved in d84a18cd1f9235b6513803ab23fa217f967057cb 126dd1be8f58a47eefa90f1a952ac5a081976160 and 98b59cc5b3c02449a4c066af82add0810fcaa9a5.
